In [78]:
import pandas as pd
import numpy as np

tabel = pd.read_csv('data_latih_opsi_2.csv', sep=',', header=None)

In [79]:
#15 bit

In [170]:
individu = 10

In [80]:
tabel = tabel.values

In [260]:
tabel[:,:]

array([[1, 0, 0, 1, 0],
       [1, 0, 1, 1, 0],
       [1, 1, 2, 1, 0],
       [1, 2, 3, 0, 1],
       [1, 3, 0, 2, 0],
       [1, 3, 1, 1, 1],
       [1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 2, 2, 1, 0],
       [1, 0, 3, 0, 1],
       [1, 2, 0, 2, 0],
       [1, 2, 1, 0, 0],
       [1, 1, 0, 1, 1],
       [1, 3, 2, 0, 1],
       [1, 1, 1, 1, 0],
       [1, 1, 3, 1, 0],
       [1, 3, 0, 0, 0],
       [1, 0, 2, 2, 0],
       [1, 1, 3, 2, 1],
       [1, 0, 2, 0, 0],
       [1, 3, 3, 0, 1],
       [1, 1, 3, 0, 0],
       [1, 2, 2, 2, 0],
       [1, 3, 2, 2, 0],
       [0, 2, 0, 2, 0],
       [0, 1, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 1, 3, 1, 1],
       [0, 3, 2, 2, 0],
       [0, 0, 3, 1, 1],
       [0, 2, 2, 0, 0],
       [0, 1, 1, 0, 1],
       [0, 2, 1, 0, 0],
       [0, 3, 3, 0, 0],
       [0, 3, 0, 2, 1],
       [0, 2, 3, 0, 0],
       [0, 2, 0, 1, 1],
       [0, 0, 2, 1, 1],
       [0, 1, 3, 2, 1],
       [0, 2, 2, 2, 0],
       [0, 1, 2, 1, 1],
       [0, 0, 1,

In [81]:
bla = tabel[0,:]

In [165]:
bla

array([1, 0, 0, 1, 0], dtype=int64)

In [132]:
def oneorzero():
    return int(np.random.rand() > .5)

In [106]:
def encode(decoded):
    bit1, bit2, bit3, bit4, bit5 = np.zeros(3), np.zeros(4), np.zeros(4), np.zeros(3), np.zeros(1)
    bit1[decoded[0]] = 1
    bit2[decoded[1]] = 1
    bit3[decoded[2]] = 1
    bit4[decoded[3]] = 1
    bit5[0] = decoded[4]
    return np.concatenate([bit1, bit2, bit3, bit4, bit5], axis=0)

In [211]:
def decode(encoded):
    bits = [None] * 5
    bits[0], bits[1], bits[2], bits[3], bits[4] = encoded[:3], encoded[3:7], encoded[7:11], encoded[11:14], encoded[-1]
    
    nbits = []
    for i, v in enumerate(bits[:-1]):
        bitz = []
        for j, k in enumerate(v):
            if k == 1:
                bitz.append(j)
        nbits.append(bitz)
    nbits.append([bits[-1]])
    return nbits

In [182]:
def initializeRule():
    krom = [None] * 5
    krom[0], krom[1], krom[2], krom[3], krom[4] = np.zeros(3), np.zeros(4), np.zeros(4), np.zeros(3), np.zeros(1)
    
    for i, v in enumerate(krom[:-1]):
        while sum(krom[i]) == 0:
            for j, k in enumerate(v):
                krom[i][j] = oneorzero()
    krom[4] = np.array([oneorzero()])
    nkrom = np.concatenate(krom)
    return nkrom

In [168]:
def initialize(individu):
    population = []
    for i in range(individu):
        population.append(np.concatenate([initializeRule(), initializeRule()], axis=0))
    return population

In [166]:
encodedData = []
for i, v in enumerate(tabel[:]):
    bitter = encode(v)
    encodedData.append(bitter)

In [167]:
encodedData

[array([0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.]),
 array([0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.]),
 array([0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0.]),
 array([0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1.]),
 array([0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0.]),
 array([0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1.]),
 array([0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1.]),
 array([0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0.]),
 array([0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1.]),
 array([0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0.]),
 array([0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0.]),
 array([0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1.]),
 array([0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1.]),
 array([0., 1., 0., 

In [164]:
initializeRule()

[array([1., 0., 0.]),
 array([1., 1., 1., 0.]),
 array([1., 0., 1., 1.]),
 array([1., 1., 0.]),
 array(0)]

In [186]:
indvs = initialize(individu)

In [193]:
print(indvs[0][:3], indvs[0][2:6], indvs[0][6:10], indvs[0][10:13], indvs[0][-1])

[0. 0. 1.] [1. 1. 1. 0.] [0. 1. 0. 1.] [0. 0. 1.] 1.0


In [215]:
ex = decode([1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
print(ex)

[[0, 1, 2], [1, 3], [0, 1, 2, 3], [0, 1, 2], [1.0]]


In [224]:
boolean = []

In [225]:
suhu = "suhu"
waktu = "waktu"
kondisi = "kondisi"
kelembapan = "kelembapan"
terbang = "terbang"

In [282]:
ez = [0, 1, 2]

# realdata = [1, 0, 0, 1, 0]
realdata = [2, 0, 1, 0, 1 ]
dtree_rules = [[[0, 1, 2], [1, 3], [0, 1, 2, 3], [0, 1, 2], [1.0]], [[1], [0], [0], [1], [0.0]], [[2], [0], [2], [2], [0.0]], [[0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3], [ 1], [1.0]], [[0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3], [ 0], [0.0]]]

bits = [None]*5
bits[0], bits[1], bits[2], bits[3], bits[4] = [], [], [], [], []

ret = "invalid"
for p, l in enumerate(dtree_rules):
    asem = []
    for i, v in enumerate(l[:-1]):
#         print("v",v)
        sem = []
        for j, k in enumerate(v):
#             print(realdata[i])
            sem.append(realdata[i] == k)
#         print(sem)
        v = any(sem)
        asem.append(v)
    if all(asem) == True:
        ret = l[-1]
        break
# truth = all(bits)
print("ret",ret)

ret [0.0]


In [252]:
any(bits[1])

False

In [253]:
truth

False

In [254]:
any([True,False])

True

In [267]:
decode([0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.])

[[1], [0], [0], [1], [0.0]]

In [271]:
decode([0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1.])

[[2], [0], [1], [1], [1.0]]

In [273]:
decode([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

[[0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2], [1.0]]