In [1]:
import pandas as pd
import numpy as np

tabel = pd.read_csv('data_latih_opsi_2.csv', sep=',', header=None)

In [2]:
#15 bit

In [3]:
individu = 10

In [4]:
tabel = tabel.values

In [5]:
data = tabel[:,:]
data

array([[1, 0, 0, 1, 0],
       [1, 0, 1, 1, 0],
       [1, 1, 2, 1, 0],
       [1, 2, 3, 0, 1],
       [1, 3, 0, 2, 0],
       [1, 3, 1, 1, 1],
       [1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 2, 2, 1, 0],
       [1, 0, 3, 0, 1],
       [1, 2, 0, 2, 0],
       [1, 2, 1, 0, 0],
       [1, 1, 0, 1, 1],
       [1, 3, 2, 0, 1],
       [1, 1, 1, 1, 0],
       [1, 1, 3, 1, 0],
       [1, 3, 0, 0, 0],
       [1, 0, 2, 2, 0],
       [1, 1, 3, 2, 1],
       [1, 0, 2, 0, 0],
       [1, 3, 3, 0, 1],
       [1, 1, 3, 0, 0],
       [1, 2, 2, 2, 0],
       [1, 3, 2, 2, 0],
       [0, 2, 0, 2, 0],
       [0, 1, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 1, 3, 1, 1],
       [0, 3, 2, 2, 0],
       [0, 0, 3, 1, 1],
       [0, 2, 2, 0, 0],
       [0, 1, 1, 0, 1],
       [0, 2, 1, 0, 0],
       [0, 3, 3, 0, 0],
       [0, 3, 0, 2, 1],
       [0, 2, 3, 0, 0],
       [0, 2, 0, 1, 1],
       [0, 0, 2, 1, 1],
       [0, 1, 3, 2, 1],
       [0, 2, 2, 2, 0],
       [0, 1, 2, 1, 1],
       [0, 0, 1,

In [6]:
# bla = tabel[0,:]

In [7]:
# bla

In [8]:
p = lambda f, i: (f[i] / sum(f))

In [9]:
def roulette(fit):
    r = np.random.uniform(0,1)
    indv = 0
    
    while r > 0:
        r -= p(fit,indv)
        
        indv += 1
    return indv-1

In [10]:
def fitness(dataset,rules):
    bnr = 0
    tot = len(dataset)
    for i, v in enumerate(dataset):
        if v[-1] == tree(v[:-1], rules):
            bnr += 1
    return bnr/tot

In [11]:
def oneorzero():
    return int(np.random.rand() > .5)

In [12]:
def encode(decoded):
    bit1, bit2, bit3, bit4, bit5 = np.zeros(3), np.zeros(4), np.zeros(4), np.zeros(3), np.zeros(1)
    bit1[decoded[0]] = 1
    bit2[decoded[1]] = 1
    bit3[decoded[2]] = 1
    bit4[decoded[3]] = 1
    bit5[0] = decoded[4]
    return np.concatenate([bit1, bit2, bit3, bit4, bit5], axis=0)

In [13]:
def decode(encoded):
    bits = [None] * 5
    bits[0], bits[1], bits[2], bits[3], bits[4] = encoded[:3], encoded[3:7], encoded[7:11], encoded[11:14], encoded[-1]
    
    nbits = []
    for i, v in enumerate(bits[:-1]):
        bitz = []
        for j, k in enumerate(v):
            if k == 1:
                bitz.append(j)
        nbits.append(bitz)
    nbits.append([bits[-1]])
    return nbits

In [14]:
def initializeRule():
    krom = [None] * 5
    krom[0], krom[1], krom[2], krom[3], krom[4] = np.zeros(3), np.zeros(4), np.zeros(4), np.zeros(3), np.zeros(1)
    
    for i, v in enumerate(krom[:-1]):
        while sum(krom[i]) == 0:
            for j, k in enumerate(v):
                krom[i][j] = oneorzero()
    krom[4] = np.array([oneorzero()])
    nkrom = np.concatenate(krom)
    return nkrom

In [15]:
def initialize(individu):
    population = []
    for i in range(individu):
        population.append(np.concatenate([initializeRule(), initializeRule()], axis=0))
    return population

In [16]:
encodedData = []
for i, v in enumerate(tabel[:]):
    bitter = encode(v)
    encodedData.append(bitter)

In [17]:
encodedData

[array([0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.]),
 array([0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.]),
 array([0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0.]),
 array([0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1.]),
 array([0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0.]),
 array([0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1.]),
 array([0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1.]),
 array([0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0.]),
 array([0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1.]),
 array([0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0.]),
 array([0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0.]),
 array([0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1.]),
 array([0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1.]),
 array([0., 1., 0., 

In [18]:
initializeRule()

array([1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0.])

In [19]:
indvs = initialize(individu)

In [20]:
print(indvs[0][:3], indvs[0][2:6], indvs[0][6:10], indvs[0][10:13], indvs[0][-1])

[0. 1. 0.] [0. 1. 1. 0.] [1. 0. 1. 1.] [1. 0. 0.] 0.0


In [21]:
ex = decode([1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
print(ex)

[[0, 1, 2], [1, 3], [0, 1, 2, 3], [0, 1, 2], [1.0]]


In [22]:
boolean = []

In [23]:
suhu = "suhu"
waktu = "waktu"
kondisi = "kondisi"
kelembapan = "kelembapan"
terbang = "terbang"

In [24]:
def tree(test, rules):
    realdata = test
#     dtree_rules = rules

    bits = [None] * 5
    bits[0], bits[1], bits[2], bits[3], bits[4] = [], [], [], [], []
#     print(rules)
    dtree_rules = [np.array_split(rules, len(rules)/15)]
#     dtree_rules = [decode(i) for i in dr]
#     for i, v in enumerate(dr):
#         print(v)
#         print(decode(v))

    ret = "invalid"
    for p, l in enumerate(dtree_rules):
        asem = []
        for i, v in enumerate(l[:-1]):
            sem = []
            for j, k in enumerate(v):
                
                
                sem.append(realdata[i] == k)
            v = any(sem)
            asem.append(v)
        if all(asem) == True:
            ret = l[-1][0]
            break
#     print("ret",ret)
    
    return ret
    

In [25]:
# ez = [0, 1, 2]

# # realdata = [1, 0, 0, 1, 0]
# realdata = [2, 0, 1, 0, 1 ]
# dtree_rules = [[[0, 1, 2], [1, 3], [0, 1, 2, 3], [0, 1, 2], [1.0]], [[1], [0], [0], [1], [0.0]], [[2], [0], [2], [2], [0.0]], [[0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3], [ 1], [1.0]], [[0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3], [ 0], [0.0]]]

# bits = [None]*5
# bits[0], bits[1], bits[2], bits[3], bits[4] = [], [], [], [], []

# ret = "invalid"
# for p, l in enumerate(dtree_rules):
#     asem = []
#     for i, v in enumerate(l[:-1]):
#         sem = []
#         for j, k in enumerate(v):
#             sem.append(realdata[i] == k)
#         v = any(sem)
#         asem.append(v)
#     if all(asem) == True:
#         ret = l[-1]
#         break
# print("ret",ret)

In [26]:
# any(bits[1])

In [27]:
# truth

In [28]:
# any([True,False])

In [29]:
decode([0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.])

[[1], [0], [0], [1], [0.0]]

In [30]:
decode([0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1.])

[[2], [0], [1], [1], [1.0]]

In [31]:
decode([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

[[0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2], [1.0]]

In [32]:
0 == 0.0

True

In [33]:
indvs = initialize(individu)

In [34]:
indvs

[array([1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1.,
        0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0.]),
 array([0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0.,
        1., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1.]),
 array([1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1.,
        0., 0., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1.]),
 array([0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1.,
        1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0.]),
 array([1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1.,
        0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0.]),
 array([1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
        1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0.]),
 array([1., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
        1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0.]),
 array([1., 0., 1., 0., 1., 1., 1.

In [35]:
for i, v in enumerate(indvs):
    print(fitness(data, v))

0.325
0.3625
0.3625
0.325
0.3625
0.325
0.3625
0.325
0.325
0.3625


In [36]:
tree([2, 0, 1, 0, 1 ], [1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1.,
        1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1.])

'invalid'

In [37]:
decode([0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0.])

[[2], [2], [1], [1], [0.0]]

In [38]:
jum = len([1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1.,
        1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1.])/15
    
    

In [39]:
jum

2.0

In [40]:
np.array_split([1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1.,
        1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1.], 2)

[array([1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0.]),
 array([1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1.])]